src/EzCMS/EzCMS.Web/Areas/Admin/Controllers/LinkTypesController.cs
using Ez.Framework.Core.Entity.RepositoryBase.Models;
using Ez.Framework.Core.Enums;
using Ez.Framework.Core.JqGrid;
using Ez.Framework.Core.JqGrid.Enums;
using Ez.Framework.Core.Mvc.Models.Editable;
using Ez.Framework.Utilities;
using EzCMS.Core.Framework.Attributes.Authorize;
using EzCMS.Core.Framework.Mvc.Controllers;
using EzCMS.Core.Framework.Navigations;
using EzCMS.Core.Models.LinkTypes;
using EzCMS.Core.Services.LinkTypes;
using Newtonsoft.Json;
using System.IO;
using System.Web.Mvc;

namespace EzCMS.Web.Areas.Admin.Controllers
{
    [EzCMSAuthorize(IsAdministrator = true)]
    public class LinkTypesController : BackendController
    {
        private readonly ILinkTypeService _linkTypeService;
        public LinkTypesController(ILinkTypeService linkTypeService)
        {
            _linkTypeService = linkTypeService;
        }

        [AdministratorNavigation("Link_Types", "Link_Holder", "Link_Types", "fa-list-ol", 20)]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public string _AjaxBinding(JqSearchIn si)
        {
            return JsonConvert.SerializeObject(_linkTypeService.SearchLinkTypes(si));
        }

        /// <summary>
        /// Export LinkTypes
        /// </summary>
        /// <param name="si"></param>
        /// <param name="gridExportMode"></param>
        /// <returns></returns>
        public ActionResult Exports(JqSearchIn si, GridExportMode gridExportMode)
        {
            var workbook = _linkTypeService.Exports(si, gridExportMode);

            var output = new MemoryStream();
            workbook.Write(output);

            return File(output.ToArray(), "application/vnd.ms-excel", "LinkTypes.xls");
        }

        #region Create		

        [AdministratorNavigation("Link_Type_Create", "Link_Types", "Link_Type_Create", "fa-plus", 10, false)]
        public ActionResult Create()
        {
            var model = _linkTypeService.GetLinkTypeManageModel();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(LinkTypeManageModel model, SubmitType submit)
        {
            if (ModelState.IsValid)
            {
                var response = _linkTypeService.SaveLinkType(model);
                SetResponseMessage(response);
                if (response.Success)
                {
                    var id = (int)response.Data;
                    switch (submit)
                    {
                        case SubmitType.Save:
                            return RedirectToAction("Index");
                        default:
                            return RedirectToAction("Edit", new { id });
                    }
                }
            }
            return View(model);
        }

        #endregion

        #region Edit

        [AdministratorNavigation("Link_Type_Edit", "Link_Types", "Link_Type_Edit", "fa-edit", 20, false)]
        public ActionResult Edit(int id)
        {
            var model = _linkTypeService.GetLinkTypeManageModel(id);
            if (!model.Id.HasValue)
            {
                SetErrorMessage(T("LinkType_Message_ObjectNotFound"));
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(LinkTypeManageModel model, string returnUrl, SubmitType submit)
        {
            if (ModelState.IsValid)
            {
                var response = _linkTypeService.SaveLinkType(model);
                SetResponseMessage(response);
                if (response.Success)
                {
                    switch (submit)
                    {
                        case SubmitType.Save:
                            if (!string.IsNullOrEmpty(returnUrl))
                            {
                                return Redirect(returnUrl);
                            }

                            return RedirectToAction("Index");
                        default:
                            return RedirectToAction("Edit", new { id = model.Id });
                    }
                }
            }
            return View(model);
        }

        #endregion

        #region Details

        [AdministratorNavigation("Link_Type_Details", "Link_Types", "Link_Type_Details", "fa-search-plus", 30, false)]
        public ActionResult Details(int id)
        {
            var model = _linkTypeService.GetLinkTypeDetailModel(id);
            if (model == null)
            {
                SetErrorMessage(T("LinkType_Message_ObjectNotFound"));
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult UpdateLinkTypeData(XEditableModel model)
        {
            if (ModelState.IsValid)
            {
                return Json(_linkTypeService.UpdateLinkTypeData(model));
            }

            return Json(new ResponseModel
            {
                Success = false,
                Message = ModelState.BuildValidationMessages()
            });
        }

        #region Methods

        [HttpPost]
        public JsonResult DeleteLinkType(int id)
        {
            return Json(_linkTypeService.DeleteLinkType(id));
        }

        #endregion

        #endregion
    }
}

src/EzCMS/EzCMS.Web/Areas/Admin/Views/LinkTypes/Create.cshtml
@model EzCMS.Core.Models.LinkTypes.LinkTypeManageModel

@{
    ViewBag.Header = T("LinkType_Site_Header");
    ViewBag.Title = T("LinkType_Site_CreateTitle");
    ViewBag.Description = T("LinkType_Site_CreateDescription");
}

<div class="page-header">
    <h1>@ViewBag.Header
        <small>
            <i class="fa fa-angle-double-right"></i>
            @ViewBag.Title
        </small>
    </h1>
</div>

<div class="row">
    <div class="col-xs-12">
        @ShowStatusMessage()
        @using (Html.BeginForm("Create", "LinkTypes", null, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.EditorForModel(Model)
        }
    </div>
</div>

src/EzCMS/EzCMS.Web/Areas/Admin/Views/LinkTypes/Details.cshtml
@model EzCMS.Core.Models.LinkTypes.LinkTypeDetailModel

@{
    ViewBag.Header = T("LinkType_Site_Header");
    ViewBag.Title = T("LinkType_Site_DetailsTitle");
    ViewBag.Description = T("LinkType_Site_DetailsDescription");
}

@section styles{
    <link rel="stylesheet" href="@Url.Content("~/Scripts/Plugins/jqGrid/css/ui.jqgrid.min.css")" />
}

<div class="page-header">
    <h1 class="pull-left">
        @ViewBag.Header
        <small>
            <i class="fa fa-angle-double-right"></i>
            @ViewBag.Title
        </small>
    </h1>
    <div class="space-8 col-xs-12 visible-xs"></div>
    <div id="top-buttons" class="col-xs-12 align-right">
        <a class="btn btn-xs btn-danger" href="javascript:deleteLinkType()">@T("System_Text_Delete")</a>
        <a class="btn btn-xs btn-primary" href="@Url.Action("Edit", new {id = Model.Id, returnUrl = Url.Action("Details", new {id = Model.Id})})">
            @T("System_Text_Edit")
        </a>
    </div>
</div>

<div class="row">
    @ShowStatusMessage()
    <div class="col-xs-12">
        <div class="form-horizontal">
            <div class="col-sm-6 col-xs-12">
                @Html.LocalizeLabelFor(m => m.LinkType.Name, new { @class = "col-sm-5 control-label align-right" })
                <div class="col-sm-7 control-value">
                    @Html.EditableFor(m => m.LinkType.Name)
                </div>
            </div>
            <div class="clear space-12"></div>

            <div class="widget-box transparent">
                <div class="widget-header">
                    <h4 class="widget-title lighter">@T("LinkType_Text_RecordInformation")</h4>
                    <div class="widget-toolbar no-border">
                        <a href="#" data-action="collapse">
                            <i class="ace-icon fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="widget-body">
                    <div class="widget-main padding-12 no-padding-left no-padding-right">
                        <div class="col-sm-6 col-xs-12">
                            <div class="form-group">
                                @Html.LocalizeLabelTimeFor(m => m.Created, new { @class = "col-sm-5 control-label align-right" })
                                <div class="col-sm-7 control-value">
                                    @Html.DisplayTimeFor(m => m.Created)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LocalizeLabelFor(m => m.CreatedBy, new { @class = "col-sm-5 control-label align-right" })
                                <div class="col-sm-7 control-value">
                                    @Model.CreatedBy
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <div class="form-group">
                                @Html.LocalizeLabelTimeFor(m => m.LastUpdate, new { @class = "col-sm-5 control-label align-right" })
                                <div class="col-sm-7 control-value">
                                    @Html.DisplayTimeFor(m => m.LastUpdate)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LocalizeLabelFor(m => m.LastUpdateBy, new { @class = "col-sm-5 control-label align-right" })
                                <div class="col-sm-7 control-value">
                                    @Model.LastUpdateBy
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="space-12 clear"></div>
            <div class="row">
                <div class="tabbable">
                    <ul class="nav nav-tabs padding-12 tab-color-blue background-grey">
                        <li class="active">
                            <a data-toggle="tab" href="#links">
                                @T("LinkType_Text_TabLinks") (<span class="create-link tab-add-button"></span>)
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="links" class="tab-pane active">
                            @Html.Partial("Details/_Links", Model.Id)
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/js/jqgrid")

    <script type="text/javascript">
        var updateUrl = "@Url.Action("UpdateLinkTypeData")";
        var pk = '@Model.Id';

        $(function () {
            if (siteHelper.getUrlParam("action") == "delete") {
                deleteLinkType();
            }
        });

        // Delete link type
        function deleteLinkType() {
            var returnUrl = siteHelper.getUrlParam("returnUrl");
            var data = { id: @Model.Id };

            siteHelper.confirm('@T("LinkType_Message_DeleteConfirm")', function (ok) {
                if (ok) {
                    siteHelper.httpPost({
                        url: "@Url.Action("DeleteLinkType")",
                        data: data,
                        success: function (response) {
                            if (response.Success) {
                                bootbox.alert(response.Message, function () {
                                    if (returnUrl != "")
                                        window.location.href = returnUrl;
                                    else
                                        window.location.href = "@Url.Action("Index")";
                                });
                            } else {
                                siteHelper.showMessage(response);
                            }
                        }
                    });
                }
            });
        }
    </script>
}

src/EzCMS/EzCMS.Web/Areas/Admin/Views/LinkTypes/Edit.cshtml
@model EzCMS.Core.Models.LinkTypes.LinkTypeManageModel

@{
    ViewBag.Header = T("LinkType_Site_Header");
    ViewBag.Title = T("LinkType_Site_EditTitle");
    ViewBag.Description = T("LinkType_Site_EditDescription");
}

<div class="page-header">
    <h1>@ViewBag.Header
        <small>
            <i class="fa fa-angle-double-right"></i>
            @ViewBag.Title
        </small>
    </h1>
</div>

<div class="row">
    <div class="col-xs-12">
        @ShowStatusMessage()
        @using (Html.BeginForm("Edit", "LinkTypes", null, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.EditorForModel(Model)
        }
    </div>
</div>

src/EzCMS/EzCMS.Web/Areas/Admin/Views/LinkTypes/Index.cshtml
@{
    ViewBag.Header = T("LinkType_Site_Header");
    ViewBag.Title = T("LinkType_Site_ListingTitle");
    ViewBag.Description = T("LinkType_Site_ListingDescription");
}

@section styles{
    <link rel="stylesheet" href="@Url.Content("~/Scripts/Plugins/jqGrid/css/ui.jqgrid.min.css")" />
}

<div class="page-header">
    <h1>
        @ViewBag.Header
        <small>
            <i class="fa fa-angle-double-right"></i>
            @ViewBag.Title
        </small>
    </h1>
</div>

<div class="row">
    <div id="grid-buttons" class="col-xs-12">
        @ShowStatusMessage()
        <a href="@Url.Action("Create")" class="btn btn-yellow btn-minier">
            <i class="fa fa-plus bigger-125"></i>
            @T("LinkType_Text_Create")
        </a>
        @Html.EmptyPartial("Partials/_ExportButtons")
    </div>
    <div class="col-xs-12">
        <!-- PAGE CONTENT BEGINS -->

        <table id="grid-table"></table>

        <div id="grid-pager"></div>

        <!-- PAGE CONTENT ENDS -->
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/js/jqgrid")

    <script type="text/javascript">
        /*
         * Setup grid
         */
        var gridSelector = "#grid-table";
        var pagerSelector = "#grid-pager";
        var navButtonsSetup = {
            enableEdit: false,
            enableCreate: false,
            enableDelete: false,
            enableSearch: true,
            enableRefresh: true,
            enableView: true
        };
        var gridSettings = $.parseJSON('@Html.Action("GetGridSettings", "Account", new { name = "Link Type" })');

        var gridOptions = {
            url: "@Url.Action("_AjaxBinding")",
            colNames: ['', '@T("LinkType_Field_Id")',
                '@T("LinkType_Field_Name")',
                '@LabelForTime(T("LinkType_Field_Created"))',
                '@T("LinkType_Field_CreatedBy")',
                '@LabelForTime(T("LinkType_Field_LastUpdate"))',
                '@T("LinkType_Field_LastUpdateBy")'
            ],
            colModel: [
                {
                    name: 'Actions',
                    hidedlg: true,
                    width: 90,
                    fixed: true,
                    sortable: false,
                    search: false,
                    align: "center",
                    formatter: function (cellvalue, options) {
                        var editIcon = "<a class='grid-action' href='@Url.Action("Edit")/" + options.rowId + "'><div class='ui-pg-div' title='@T("System_Text_Edit")'><span class='fa fa-edit'></span></div></a>";
                        var detailsIcon = "<a class='grid-action' href='@Url.Action("Details")/" + options.rowId + "'><div class='ui-pg-div' title='@T("System_Text_ViewDetails")'><span class='fa fa-search-plus'></span></div></a>";
                        var deleteIcon = "<a class='grid-action' href='@Url.Action("Details")/" + options.rowId + "?action=delete'><div class='ui-pg-div'title='@T("System_Text_Delete")'><span class='fa fa-times red'></span></div></a>";
                        return editIcon + detailsIcon + deleteIcon;
                    }
                },
                { name: 'Id', index: 'Id', key: true, width: 60, fixed: true, align: 'center', sorttype: "int", searchoptions: { sopt: ['eq'] } },
                { name: 'Name', index: 'Name' },
                { name: 'Created', index: 'Created', hidden: true, sorttype: "datetime", search: false, formatter: function (cellValue, options, rowObject) { return jqGridHelper.printLocalDateTimeFormat(cellValue); } },
                { name: 'CreatedBy', index: 'CreatedBy', hidden: true },
                { name: 'LastUpdate', index: 'LastUpdate', sorttype: "datetime", search: false, formatter: function (cellValue, options, rowObject) { return jqGridHelper.printLocalDateTimeFormat(cellValue); } },
                { name: 'LastUpdateBy', index: 'LastUpdateBy' }
            ]
        };

        jqGridHelper.setupGrid(gridSelector, pagerSelector, gridOptions, gridSettings, navButtonsSetup, "@Url.Action("Exports")");
    </script>
}